### ISSUE TITLE
Rate Limiter: ETS by default with Redis as option

### ISSUE THREAD

**Issue by cpursley** [eventrelay/eventrelay#20]
I had to bypass the case logic here to get things running: https://github.com/eventrelay/eventrelay/blob/ad91d3ae4f557f231b638e0b5e36743686fd97c1/lib/event_relay_web/rate_limiter.ex#L5

Rate limiting in general is probably prudent. Redis seems like an unnecessary dependency (when Erlang can handle caching natively - I see that nebulex is already installed).

**Comment by themusicman** [comment]
I agree that I would rather not have the Redis dependency. I have thought about writing a Hammer adapter for nebulex. Looking at the Redis adapter is seems pretty straightforward. https://github.com/ExHammer/hammer-backend-redis/blob/master/lib/hammer_backend_redis.ex

**Comment by cpursley** [comment]
What about just using https://github.com/ExHammer/hammer-backend-mnesia ?
