### ISSUE TITLE
Add Predicated support to Subscriptions

### ISSUE THREAD

**Issue by themusicman** [eventrelay/eventrelay#28]
https://github.com/themusicman/predicated

Add the ability to filter events using predicated query strings

**Comment by cpursley** [comment]
I guess the idea here is the filtering is done on the x_events.data jsonb field (after getting decoded to Map)?

**Comment by themusicman** [comment]
The whole event struct will be able to be queried but I am also adding a `to_sql` function in Predicated to convert the predicates to where clauses on a Ecto query.
