### ISSUE TITLE
Migrate to use StandardWebhooks

### ISSUE THREAD

**Issue by themusicman** [eventrelay/eventrelay#55]
https://www.standardwebhooks.com/
https://github.com/standard-webhooks/standard-webhooks/tree/main

- When accepting inbound webhooks test for the usage of it and handle properly.
- When sending webhooks conform to the standard

**Comment by themusicman** [comment]
@cpursley If you are going to work on the Elixir library to contribute to the StandardWebhooks project I will wait until that is done for this.

**Comment by cpursley** [comment]
Sounds good. If they don't accept a PR we can just use the code ourselves.
