### ISSUE TITLE
Ability to transform events

### ISSUE THREAD

**Issue by themusicman** [eventrelay/eventrelay#69]
Ideas:

1. Create an Elixir JSON transformation library that users a template defines the structure of the new JSON and uses JSONpaths to define the values.
2. Add support for Elixir module based transformers. Think transformer contains config map that can configure how a transformer module transforms the data. Developer users could inject modules using a Dockerfile to add their own custom transformers. Or community supported transformers can be added via pull results. 
3. Lua script based transformations (already exists)
4. Liquid template based transformations

**Comment by cpursley** [comment]
I don't think the target user will be Elixir users (I could be wrong)

My vote is 4: I think we should see how far we can get with the Liquid approach. Maybe add a custom `request` function/tag that could call and return data from say, serverless for those who want to use JS or Python.

Second place vote is 2.

**Comment by cpursley** [comment]
Also, I wonder if we should have the concept of _before_ and _after_ Transformers (before Event is saved). Or maybe we enforce that Event.data is always saved in the format in which it arrived (source of truth)?

**Comment by themusicman** [comment]
> Also, I wonder if we should have the concept of before and after Transformers (before Event is saved). Or maybe we enforce that Event.data is always saved in the format in which it arrived (source of truth)

I think transformers will be needed from ingesting data from a source, when forwarding an event to another topic and when sending an event to a destination.
